_enabled_ordered = ["Alphabet", "Navigation", "NavigationNon", "Numbers", "Punctuation", "Keyboard", "CasterRule", "CasterMicRule", "HardwareRule", "MouseAlternativesRule", "DouglasGridRule", "RainbowGridRule", "SudokuGridRule", "HMCRule", "HMCDirectoryRule", "HMCHistoryRule", "HMCLaunchRule", "HMCSettingsRule", "HistoryRule", "ChainAlias", "Alias", "BringRule", "Again", "LegionGridRule", "IERule", "GrammarActivatorRule", "HooksActivationRule", "TransformersActivationRule", "DictationSinkRule", "WindowSwitchingRule", "WordDeleteRule", "FirefoxRule", "VSCodeCcrRule", "VSCodeNonCcrRule", "WindowManagementRule", "FirefoxExtendedRule", "HMCConfirmRule"]
_internal = ["GrammarActivatorRule", "HooksActivationRule", "TransformersActivationRule", "ManualGrammarReloadRule"]

[whitelisted]
WindowSwitchingRule = true
Alphabet = true
Navigation = true
NavigationNon = true
Numbers = true
Punctuation = true
Keyboard = true
CasterRule = true
CasterMicRule = true
HardwareRule = true
MouseAlternativesRule = true
WindowManagementRule = true
DouglasGridRule = true
RainbowGridRule = true
SudokuGridRule = true
HMCRule = true
HMCConfirmRule = true
HMCDirectoryRule = true
HMCHistoryRule = true
HMCLaunchRule = true
HMCSettingsRule = true
HistoryRule = true
ChainAlias = true
Alias = true
BringRule = true
Again = true
LegionGridRule = true
IERule = true
SikuliRule = true
SikuliManagementRule = true
JetbrainsRule = true
CSS = true
JiraRule = true
ChromeRule = true
FirefoxRule = true
GitterRule = true
MSTeamsRule = true
WebexTeamsRule = true
AtomRule = true
EmacsRule = true
FlashDevelopRule = true
LyxRule = true
MSVCRule = true
NPPRule = true
RStudioRule = true
SQLDeveloperRule = true
SSMSRule = true
SublimeRule = true
TyporaRule = true
UnityRule = true
VisualStudioRule = true
EclipseCCR = true
EclipseRule = true
VSCodeCcrRule = true
VSCodeNonCcrRule = true
fmanRule = true
TotalCommanderRule = true
SyncDirsRule = true
GitHubDeskRule = true
KDiff3Rule = true
ExcelRule = true
OutlookRule = true
AcrobatRule = true
FoxitRule = true
WindowsSpeechRecognitionRule = true
DragonRule = true
SpellingWindowRule = true
GitBashRule = true
FileDialogueRule = true
MSWordRule = true
Bash = true
CPP = true
CSharp = true
Dart = true
Go = true
Haxe = true
HTML = true
Javascript = true
Java = true
JavaNon = true
LaTeX = true
Markdown = true
Matlab = true
MatlabNon = true
Prolog = true
PrologNon = true
Python = true
PythonNon = true
Rust = true
RustNon = true
Rlang = true
SQL = true
VHDL = true
VHDLnon = true
VoiceDevCommands = true
DictationSinkRule = true
TextManipulation = true
WordDeleteRule = true
FirefoxExtendedRule = true
